# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chrx/dev/mark_project/sdl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chrx/dev/mark_project/sdl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chrx/dev/mark_project/sdl/CMakeFiles /home/chrx/dev/mark_project/sdl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chrx/dev/mark_project/sdl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CodeGUI

# Build rule for target.
CodeGUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CodeGUI
.PHONY : CodeGUI

# fast build rule for target.
CodeGUI/fast:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/build
.PHONY : CodeGUI/fast

sdl/SDLWindowManager.o: sdl/SDLWindowManager.cpp.o

.PHONY : sdl/SDLWindowManager.o

# target to build an object file
sdl/SDLWindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdl/SDLWindowManager.cpp.o
.PHONY : sdl/SDLWindowManager.cpp.o

sdl/SDLWindowManager.i: sdl/SDLWindowManager.cpp.i

.PHONY : sdl/SDLWindowManager.i

# target to preprocess a source file
sdl/SDLWindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdl/SDLWindowManager.cpp.i
.PHONY : sdl/SDLWindowManager.cpp.i

sdl/SDLWindowManager.s: sdl/SDLWindowManager.cpp.s

.PHONY : sdl/SDLWindowManager.s

# target to generate assembly for a file
sdl/SDLWindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdl/SDLWindowManager.cpp.s
.PHONY : sdl/SDLWindowManager.cpp.s

sdl/TextField.o: sdl/TextField.cpp.o

.PHONY : sdl/TextField.o

# target to build an object file
sdl/TextField.cpp.o:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdl/TextField.cpp.o
.PHONY : sdl/TextField.cpp.o

sdl/TextField.i: sdl/TextField.cpp.i

.PHONY : sdl/TextField.i

# target to preprocess a source file
sdl/TextField.cpp.i:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdl/TextField.cpp.i
.PHONY : sdl/TextField.cpp.i

sdl/TextField.s: sdl/TextField.cpp.s

.PHONY : sdl/TextField.s

# target to generate assembly for a file
sdl/TextField.cpp.s:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdl/TextField.cpp.s
.PHONY : sdl/TextField.cpp.s

sdlMain.o: sdlMain.cpp.o

.PHONY : sdlMain.o

# target to build an object file
sdlMain.cpp.o:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdlMain.cpp.o
.PHONY : sdlMain.cpp.o

sdlMain.i: sdlMain.cpp.i

.PHONY : sdlMain.i

# target to preprocess a source file
sdlMain.cpp.i:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdlMain.cpp.i
.PHONY : sdlMain.cpp.i

sdlMain.s: sdlMain.cpp.s

.PHONY : sdlMain.s

# target to generate assembly for a file
sdlMain.cpp.s:
	$(MAKE) -f CMakeFiles/CodeGUI.dir/build.make CMakeFiles/CodeGUI.dir/sdlMain.cpp.s
.PHONY : sdlMain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CodeGUI"
	@echo "... sdl/SDLWindowManager.o"
	@echo "... sdl/SDLWindowManager.i"
	@echo "... sdl/SDLWindowManager.s"
	@echo "... sdl/TextField.o"
	@echo "... sdl/TextField.i"
	@echo "... sdl/TextField.s"
	@echo "... sdlMain.o"
	@echo "... sdlMain.i"
	@echo "... sdlMain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

